### ISSUE TITLE
Installing ROS2 on JetBot - what OS were you using?

### ISSUE THREAD

**Issue by brianlmerritt** [jdgalviss/jetbot-ros2#10]
ROS2 normally runs on Ubuntu 20.04, but it isn't clear here if you were running an upgraded Ubuntu 18.04 to 20.04 or using some other method.  Can you please update here or in your readme which base OS and/or JetPack version you were booting from please.

**Comment by jdgalviss** [comment]
Hi. I used ROS 2 eloquent which is a distro for Ubuntu 18.04. https://docs.ros.org/en/eloquent/Installation.html

**Comment by brianlmerritt** [comment]
Sorry, have only used ROS2 since foxy.  Thanks for coming back so quickly
