### ISSUE TITLE
Version of the Python Packages

### ISSUE THREAD

**Issue by timovr-dev** [jdgalviss/jetbot-ros2#6]
I'm trying to rebuild your project with a Jetson Xavier NX.

During the installation of the python package: 
`pip3 install aiortc` 
pip tries to install the newest version available which results in some errors (gcc compiler errors).
Afterwards I tested it with an older version of aiortc and it worked instantly.

I really would appreciate if you could tell me the specific versions for the following packages on your rover system: 
- aiortc
- aiohttp
- pyfakewebcam

**Comment by jdgalviss** [comment]
The versions I used are: 

- aiortc: 0.9.28
- aiohttp: 3.6.2
- pyfakewebcam: 0.1.0

I have been a little bit busy but as soon as I have some time I will work on a clean installation, perhaps using docker for all the dependencies.

**Comment by timovr-dev** [comment]
Thank you this helps a lot!
And yes docker would be awesome for reproducibility.

**Comment by timovr-dev** [comment]
I found a solution to the error: 
The package **aiortc** depends on the package **av** which needs **ffmpeg** to be installed.
If the ffmpeg version is less than 4 the installation with pip3 will not succeed. (`ffmpeg -version`)

**Solution:**
`sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt upgrade`

Sometimes `libavcodec-dev` also needs to be upgraded as described here: https://github.com/aiortc/aiortc/issues/326#issuecomment-666235469
