### ISSUE TITLE
How can I change the speed of scan??

### ISSUE THREAD

**Issue by giry-ankoro** [jdgalviss/jetbot-ros2#7]
Hi!

I would like to change the speed of scan.
I guess I should change fps rate, but not sure....

Is it possible to do that??

Thank you

**Comment by jdgalviss** [comment]
Hi, yes, in the realsense_ros2 package's launch file realsense_launch.py there is a parameter called fps. However note that due to limited computing power the Jetson Nano will only run properly at 6 fps. At faster rates you will start noticing larger latencies. I hope this helps
