### ISSUE TITLE
“colcon build --symlink-install" Failed

### ISSUE THREAD

**Issue by Roswellii** [jdgalviss/jetbot-ros2#8]
How can I solve this problem? Thanks!!

root@davinci-mini:/usr/repo/jetbot-ros2/dev_ws# colcon build --symlink-install
Starting >>> nav2_common
Starting >>> nav_2d_msgs
Starting >>> behaviortree_cpp_v3                                            
Starting >>> motion_control
--- stderr: nav2_common                                                                                                                            
Traceback (most recent call last):
  File "/opt/ros/eloquent/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py", line 21, in <module>
    from catkin_pkg.package import parse_package_string
ModuleNotFoundError: No module named 'catkin_pkg'
CMake Error at /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:94 (message):
  execute_process(/usr/local/python3.7.5/bin/python3
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py
  /usr/repo/jetbot-ros2/dev_ws/src/navigation2/nav2_common/package.xml
  /usr/repo/jetbot-ros2/dev_ws/build/nav2_common/ament_cmake_core/package.cmake)
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:49 (_ament_package_xml)
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package.cmake:63 (ament_package_xml)
  CMakeLists.txt:10 (ament_package)

---
Failed   <<< nav2_common [2.06s, exited with code 1]
--- stderr: behaviortree_cpp_v3
Traceback (most recent call last):
  File "/opt/ros/eloquent/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py", line 21, in <module>
    from catkin_pkg.package import parse_package_string
ModuleNotFoundError: No module named 'catkin_pkg'
CMake Error at /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:94 (message):
  execute_process(/usr/local/python3.7.5/bin/python3
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py
  /usr/repo/jetbot-ros2/dev_ws/src/BehaviorTree.CPP/package.xml
  /usr/repo/jetbot-ros2/dev_ws/build/behaviortree_cpp_v3/ament_cmake_core/package.cmake)
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:49 (_ament_package_xml)
  /opt/ros/eloquent/share/ament_cmake_core/cmake/core/ament_package.cmake:63 (ament_package_xml)
  CMakeLists.txt:123 (ament_package)

---
Failed   <<< behaviortree_cpp_v3 [2.01s, exited with code 1]
Aborted  <<< nav_2d_msgs [2.60s]                                                                
Aborted  <<< motion_control [4.72s]                      

Summary: 0 packages finished [7.55s]
  2 packages failed: behaviortree_cpp_v3 nav2_common
  2 packages aborted: motion_control nav_2d_msgs
  3 packages had stderr output: behaviortree_cpp_v3 nav2_common nav_2d_msgs
  31 packages not processed

**Comment by jdgalviss** [comment]
I haven't encountered this error yet. However, did you make sure to clone the navigation 2 repo in the 'eloquent-devel' branch? I noticed there was a typo in the README, so maybe that was the problem. I already fixed it. Anyways, this is the command to clone the repo in the right branch:
`git clone https://github.com/ros-planning/navigation2.git --branch eloquent-devel`
